version: '3'

services:
  whitesnake_proj:
  web:
    container_name: django
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app1
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
volumes:
  db: